# Generated by Django 4.1.7 on 2023-04-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
