# Generated by Django 4.1.7 on 2023-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sms_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='createdAt',
            new_name='sentDate',
        ),
    ]
